databases:
  - name: nodepair
    databaseName: nodepair
    user: nodepair

services:
  - type: web
    name: nodepair
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "daphne -b 0.0.0.0 nodepair.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nodepair
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4